"""user_referrer

Revision ID: cc3aa45b60fd
Revises: 33f24d9e3208
Create Date: 2025-06-02 12:09:27.569755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3aa45b60fd'
down_revision: Union[str, None] = '33f24d9e3208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###